### ISSUE TITLE
IdenticalCompuMethod instance in the createanycompumethod.create_any_compu_method_from_et function is missing three required arguments

### ISSUE THREAD

**Issue by nada-ben-ali** [mercedes-benz/odxtools#331]
The [IdenticalCompuMethod instance  in the createanycompumethod.create_any_compu_method_from_et function](https://github.com/mercedes-benz/odxtools/blob/7.3.0/odxtools/compumethods/createanycompumethod.py#L40) is missing three required positional arguments: 'category', 'compu_internal_to_phys', and 'compu_phys_to_internal'.

odxtools version: [7.3.0](https://github.com/mercedes-benz/odxtools/releases/tag/7.3.0)

![image](https://github.com/user-attachments/assets/2d6e4457-1e3e-4eba-b31a-b8db6973bb7f)

![image](https://github.com/user-attachments/assets/eebae4f7-edbd-44c2-98e5-88636bc5b566)

**Comment by kayoub5** [comment]
@andlaus FYI

**Comment by andlaus** [comment]
okay, this is a bug that must be fixed (I'll do so tomorrow). That said, this code is only excuted if the compu method in question is not known (most likely because it is not implemented. there still are a few of them in odxtools). Can you find out what kind of compu method is featured by your dataset? (i.e. what are the the contents of the `CATEGORY` subtag?)

**Comment by nada-ben-ali** [comment]
@andlaus the compu category is **SCALE-RAT-FUNC**.

**Comment by andlaus** [comment]
ok, thanks. I suppose I should put some effort into implementing the remaining compu methods. BTW: SCALE-RAT-FUNC is a bit weird IMO because it is not invertible, i.e. encoding a parameter which uses such a compu function is going to be "fun"...
